[package]
name = "collatz_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
plotpy = "1.10.1"
rayon = "1.10.0"

[dev-dependencies]
criterion = {version = "0.5.1", features = ["html_reports"]}

[[bench]]
name = "my_benchmark"
harness = false
